#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMNNPM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLTC")]
	public partial class DataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCA(CA instance);
    partial void UpdateCA(CA instance);
    partial void DeleteCA(CA instance);
    partial void InsertTIECCUOI(TIECCUOI instance);
    partial void UpdateTIECCUOI(TIECCUOI instance);
    partial void DeleteTIECCUOI(TIECCUOI instance);
    partial void InsertDANHSACHDV(DANHSACHDV instance);
    partial void UpdateDANHSACHDV(DANHSACHDV instance);
    partial void DeleteDANHSACHDV(DANHSACHDV instance);
    partial void InsertDICHVU(DICHVU instance);
    partial void UpdateDICHVU(DICHVU instance);
    partial void DeleteDICHVU(DICHVU instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertLOAISANH(LOAISANH instance);
    partial void UpdateLOAISANH(LOAISANH instance);
    partial void DeleteLOAISANH(LOAISANH instance);
    partial void InsertMONAN(MONAN instance);
    partial void UpdateMONAN(MONAN instance);
    partial void DeleteMONAN(MONAN instance);
    partial void InsertSANH(SANH instance);
    partial void UpdateSANH(SANH instance);
    partial void DeleteSANH(SANH instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertTHUCDON(THUCDON instance);
    partial void UpdateTHUCDON(THUCDON instance);
    partial void DeleteTHUCDON(THUCDON instance);
    #endregion
		
		public DataDataContext() : 
				base(global::CMNNPM.Properties.Settings.Default.QLTCConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CA> CAs
		{
			get
			{
				return this.GetTable<CA>();
			}
		}
		
		public System.Data.Linq.Table<TIECCUOI> TIECCUOIs
		{
			get
			{
				return this.GetTable<TIECCUOI>();
			}
		}
		
		public System.Data.Linq.Table<DANHSACHDV> DANHSACHDVs
		{
			get
			{
				return this.GetTable<DANHSACHDV>();
			}
		}
		
		public System.Data.Linq.Table<DICHVU> DICHVUs
		{
			get
			{
				return this.GetTable<DICHVU>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAISANH> LOAISANHs
		{
			get
			{
				return this.GetTable<LOAISANH>();
			}
		}
		
		public System.Data.Linq.Table<MONAN> MONANs
		{
			get
			{
				return this.GetTable<MONAN>();
			}
		}
		
		public System.Data.Linq.Table<SANH> SANHs
		{
			get
			{
				return this.GetTable<SANH>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<THUCDON> THUCDONs
		{
			get
			{
				return this.GetTable<THUCDON>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CA")]
	public partial class CA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACA;
		
		private string _TENCA;
		
		private EntitySet<TIECCUOI> _TIECCUOIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACAChanging(string value);
    partial void OnMACAChanged();
    partial void OnTENCAChanging(string value);
    partial void OnTENCAChanged();
    #endregion
		
		public CA()
		{
			this._TIECCUOIs = new EntitySet<TIECCUOI>(new Action<TIECCUOI>(this.attach_TIECCUOIs), new Action<TIECCUOI>(this.detach_TIECCUOIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACA", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACA
		{
			get
			{
				return this._MACA;
			}
			set
			{
				if ((this._MACA != value))
				{
					this.OnMACAChanging(value);
					this.SendPropertyChanging();
					this._MACA = value;
					this.SendPropertyChanged("MACA");
					this.OnMACAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCA", DbType="NVarChar(50)")]
		public string TENCA
		{
			get
			{
				return this._TENCA;
			}
			set
			{
				if ((this._TENCA != value))
				{
					this.OnTENCAChanging(value);
					this.SendPropertyChanging();
					this._TENCA = value;
					this.SendPropertyChanged("TENCA");
					this.OnTENCAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CA_TIECCUOI", Storage="_TIECCUOIs", ThisKey="MACA", OtherKey="MACA")]
		public EntitySet<TIECCUOI> TIECCUOIs
		{
			get
			{
				return this._TIECCUOIs;
			}
			set
			{
				this._TIECCUOIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TIECCUOIs(TIECCUOI entity)
		{
			this.SendPropertyChanging();
			entity.CA = this;
		}
		
		private void detach_TIECCUOIs(TIECCUOI entity)
		{
			this.SendPropertyChanging();
			entity.CA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIECCUOI")]
	public partial class TIECCUOI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATIECCUOI;
		
		private string _MAKHACHHANG;
		
		private string _MASANH;
		
		private string _MATHUCDON;
		
		private string _MADANHSACHDV;
		
		private string _NGAYDATTIEC;
		
		private System.Nullable<int> _SLBAN;
		
		private System.Nullable<int> _SLBANDUTRU;
		
		private string _MACA;
		
		private EntitySet<DANHSACHDV> _DANHSACHDVs;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntitySet<THUCDON> _THUCDONs;
		
		private EntityRef<CA> _CA;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<SANH> _SANH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATIECCUOIChanging(string value);
    partial void OnMATIECCUOIChanged();
    partial void OnMAKHACHHANGChanging(string value);
    partial void OnMAKHACHHANGChanged();
    partial void OnMASANHChanging(string value);
    partial void OnMASANHChanged();
    partial void OnMATHUCDONChanging(string value);
    partial void OnMATHUCDONChanged();
    partial void OnMADANHSACHDVChanging(string value);
    partial void OnMADANHSACHDVChanged();
    partial void OnNGAYDATTIECChanging(string value);
    partial void OnNGAYDATTIECChanged();
    partial void OnSLBANChanging(System.Nullable<int> value);
    partial void OnSLBANChanged();
    partial void OnSLBANDUTRUChanging(System.Nullable<int> value);
    partial void OnSLBANDUTRUChanged();
    partial void OnMACAChanging(string value);
    partial void OnMACAChanged();
    #endregion
		
		public TIECCUOI()
		{
			this._DANHSACHDVs = new EntitySet<DANHSACHDV>(new Action<DANHSACHDV>(this.attach_DANHSACHDVs), new Action<DANHSACHDV>(this.detach_DANHSACHDVs));
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._THUCDONs = new EntitySet<THUCDON>(new Action<THUCDON>(this.attach_THUCDONs), new Action<THUCDON>(this.detach_THUCDONs));
			this._CA = default(EntityRef<CA>);
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._SANH = default(EntityRef<SANH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATIECCUOI", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATIECCUOI
		{
			get
			{
				return this._MATIECCUOI;
			}
			set
			{
				if ((this._MATIECCUOI != value))
				{
					this.OnMATIECCUOIChanging(value);
					this.SendPropertyChanging();
					this._MATIECCUOI = value;
					this.SendPropertyChanged("MATIECCUOI");
					this.OnMATIECCUOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHACHHANG", DbType="Char(20)")]
		public string MAKHACHHANG
		{
			get
			{
				return this._MAKHACHHANG;
			}
			set
			{
				if ((this._MAKHACHHANG != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._MAKHACHHANG = value;
					this.SendPropertyChanged("MAKHACHHANG");
					this.OnMAKHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASANH", DbType="Char(20)")]
		public string MASANH
		{
			get
			{
				return this._MASANH;
			}
			set
			{
				if ((this._MASANH != value))
				{
					if (this._SANH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMASANHChanging(value);
					this.SendPropertyChanging();
					this._MASANH = value;
					this.SendPropertyChanged("MASANH");
					this.OnMASANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUCDON", DbType="Char(20)")]
		public string MATHUCDON
		{
			get
			{
				return this._MATHUCDON;
			}
			set
			{
				if ((this._MATHUCDON != value))
				{
					this.OnMATHUCDONChanging(value);
					this.SendPropertyChanging();
					this._MATHUCDON = value;
					this.SendPropertyChanged("MATHUCDON");
					this.OnMATHUCDONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADANHSACHDV", DbType="Char(20)")]
		public string MADANHSACHDV
		{
			get
			{
				return this._MADANHSACHDV;
			}
			set
			{
				if ((this._MADANHSACHDV != value))
				{
					this.OnMADANHSACHDVChanging(value);
					this.SendPropertyChanging();
					this._MADANHSACHDV = value;
					this.SendPropertyChanged("MADANHSACHDV");
					this.OnMADANHSACHDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDATTIEC", DbType="VarChar(50)")]
		public string NGAYDATTIEC
		{
			get
			{
				return this._NGAYDATTIEC;
			}
			set
			{
				if ((this._NGAYDATTIEC != value))
				{
					this.OnNGAYDATTIECChanging(value);
					this.SendPropertyChanging();
					this._NGAYDATTIEC = value;
					this.SendPropertyChanged("NGAYDATTIEC");
					this.OnNGAYDATTIECChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLBAN", DbType="Int")]
		public System.Nullable<int> SLBAN
		{
			get
			{
				return this._SLBAN;
			}
			set
			{
				if ((this._SLBAN != value))
				{
					this.OnSLBANChanging(value);
					this.SendPropertyChanging();
					this._SLBAN = value;
					this.SendPropertyChanged("SLBAN");
					this.OnSLBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLBANDUTRU", DbType="Int")]
		public System.Nullable<int> SLBANDUTRU
		{
			get
			{
				return this._SLBANDUTRU;
			}
			set
			{
				if ((this._SLBANDUTRU != value))
				{
					this.OnSLBANDUTRUChanging(value);
					this.SendPropertyChanging();
					this._SLBANDUTRU = value;
					this.SendPropertyChanged("SLBANDUTRU");
					this.OnSLBANDUTRUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACA", DbType="Char(20)")]
		public string MACA
		{
			get
			{
				return this._MACA;
			}
			set
			{
				if ((this._MACA != value))
				{
					if (this._CA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACAChanging(value);
					this.SendPropertyChanging();
					this._MACA = value;
					this.SendPropertyChanged("MACA");
					this.OnMACAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIECCUOI_DANHSACHDV", Storage="_DANHSACHDVs", ThisKey="MATIECCUOI", OtherKey="MATIECCUOI")]
		public EntitySet<DANHSACHDV> DANHSACHDVs
		{
			get
			{
				return this._DANHSACHDVs;
			}
			set
			{
				this._DANHSACHDVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIECCUOI_HOADON", Storage="_HOADONs", ThisKey="MATIECCUOI", OtherKey="MATIECCUOI")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIECCUOI_THUCDON", Storage="_THUCDONs", ThisKey="MATIECCUOI", OtherKey="MATIECCUOI")]
		public EntitySet<THUCDON> THUCDONs
		{
			get
			{
				return this._THUCDONs;
			}
			set
			{
				this._THUCDONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CA_TIECCUOI", Storage="_CA", ThisKey="MACA", OtherKey="MACA", IsForeignKey=true)]
		public CA CA
		{
			get
			{
				return this._CA.Entity;
			}
			set
			{
				CA previousValue = this._CA.Entity;
				if (((previousValue != value) 
							|| (this._CA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CA.Entity = null;
						previousValue.TIECCUOIs.Remove(this);
					}
					this._CA.Entity = value;
					if ((value != null))
					{
						value.TIECCUOIs.Add(this);
						this._MACA = value.MACA;
					}
					else
					{
						this._MACA = default(string);
					}
					this.SendPropertyChanged("CA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_TIECCUOI", Storage="_KHACHHANG", ThisKey="MAKHACHHANG", OtherKey="MAKHACHHANG", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.TIECCUOIs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.TIECCUOIs.Add(this);
						this._MAKHACHHANG = value.MAKHACHHANG;
					}
					else
					{
						this._MAKHACHHANG = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANH_TIECCUOI", Storage="_SANH", ThisKey="MASANH", OtherKey="MASANH", IsForeignKey=true)]
		public SANH SANH
		{
			get
			{
				return this._SANH.Entity;
			}
			set
			{
				SANH previousValue = this._SANH.Entity;
				if (((previousValue != value) 
							|| (this._SANH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SANH.Entity = null;
						previousValue.TIECCUOIs.Remove(this);
					}
					this._SANH.Entity = value;
					if ((value != null))
					{
						value.TIECCUOIs.Add(this);
						this._MASANH = value.MASANH;
					}
					else
					{
						this._MASANH = default(string);
					}
					this.SendPropertyChanged("SANH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANHSACHDVs(DANHSACHDV entity)
		{
			this.SendPropertyChanging();
			entity.TIECCUOI = this;
		}
		
		private void detach_DANHSACHDVs(DANHSACHDV entity)
		{
			this.SendPropertyChanging();
			entity.TIECCUOI = null;
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TIECCUOI = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TIECCUOI = null;
		}
		
		private void attach_THUCDONs(THUCDON entity)
		{
			this.SendPropertyChanging();
			entity.TIECCUOI = this;
		}
		
		private void detach_THUCDONs(THUCDON entity)
		{
			this.SendPropertyChanging();
			entity.TIECCUOI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHSACHDV")]
	public partial class DANHSACHDV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADANHSACHDV;
		
		private string _MATIECCUOI;
		
		private string _MADICHVU;
		
		private System.Nullable<int> _SOLUONG;
		
		private EntityRef<TIECCUOI> _TIECCUOI;
		
		private EntityRef<DICHVU> _DICHVU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADANHSACHDVChanging(string value);
    partial void OnMADANHSACHDVChanged();
    partial void OnMATIECCUOIChanging(string value);
    partial void OnMATIECCUOIChanged();
    partial void OnMADICHVUChanging(string value);
    partial void OnMADICHVUChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    #endregion
		
		public DANHSACHDV()
		{
			this._TIECCUOI = default(EntityRef<TIECCUOI>);
			this._DICHVU = default(EntityRef<DICHVU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADANHSACHDV", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADANHSACHDV
		{
			get
			{
				return this._MADANHSACHDV;
			}
			set
			{
				if ((this._MADANHSACHDV != value))
				{
					this.OnMADANHSACHDVChanging(value);
					this.SendPropertyChanging();
					this._MADANHSACHDV = value;
					this.SendPropertyChanged("MADANHSACHDV");
					this.OnMADANHSACHDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATIECCUOI", DbType="Char(20)")]
		public string MATIECCUOI
		{
			get
			{
				return this._MATIECCUOI;
			}
			set
			{
				if ((this._MATIECCUOI != value))
				{
					if (this._TIECCUOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATIECCUOIChanging(value);
					this.SendPropertyChanging();
					this._MATIECCUOI = value;
					this.SendPropertyChanged("MATIECCUOI");
					this.OnMATIECCUOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADICHVU", DbType="Char(20)")]
		public string MADICHVU
		{
			get
			{
				return this._MADICHVU;
			}
			set
			{
				if ((this._MADICHVU != value))
				{
					if (this._DICHVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADICHVUChanging(value);
					this.SendPropertyChanging();
					this._MADICHVU = value;
					this.SendPropertyChanged("MADICHVU");
					this.OnMADICHVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIECCUOI_DANHSACHDV", Storage="_TIECCUOI", ThisKey="MATIECCUOI", OtherKey="MATIECCUOI", IsForeignKey=true)]
		public TIECCUOI TIECCUOI
		{
			get
			{
				return this._TIECCUOI.Entity;
			}
			set
			{
				TIECCUOI previousValue = this._TIECCUOI.Entity;
				if (((previousValue != value) 
							|| (this._TIECCUOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TIECCUOI.Entity = null;
						previousValue.DANHSACHDVs.Remove(this);
					}
					this._TIECCUOI.Entity = value;
					if ((value != null))
					{
						value.DANHSACHDVs.Add(this);
						this._MATIECCUOI = value.MATIECCUOI;
					}
					else
					{
						this._MATIECCUOI = default(string);
					}
					this.SendPropertyChanged("TIECCUOI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DICHVU_DANHSACHDV", Storage="_DICHVU", ThisKey="MADICHVU", OtherKey="MADICHVU", IsForeignKey=true)]
		public DICHVU DICHVU
		{
			get
			{
				return this._DICHVU.Entity;
			}
			set
			{
				DICHVU previousValue = this._DICHVU.Entity;
				if (((previousValue != value) 
							|| (this._DICHVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DICHVU.Entity = null;
						previousValue.DANHSACHDVs.Remove(this);
					}
					this._DICHVU.Entity = value;
					if ((value != null))
					{
						value.DANHSACHDVs.Add(this);
						this._MADICHVU = value.MADICHVU;
					}
					else
					{
						this._MADICHVU = default(string);
					}
					this.SendPropertyChanged("DICHVU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DICHVU")]
	public partial class DICHVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADICHVU;
		
		private string _TENDICHVU;
		
		private string _GIA;
		
		private EntitySet<DANHSACHDV> _DANHSACHDVs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADICHVUChanging(string value);
    partial void OnMADICHVUChanged();
    partial void OnTENDICHVUChanging(string value);
    partial void OnTENDICHVUChanged();
    partial void OnGIAChanging(string value);
    partial void OnGIAChanged();
    #endregion
		
		public DICHVU()
		{
			this._DANHSACHDVs = new EntitySet<DANHSACHDV>(new Action<DANHSACHDV>(this.attach_DANHSACHDVs), new Action<DANHSACHDV>(this.detach_DANHSACHDVs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADICHVU", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADICHVU
		{
			get
			{
				return this._MADICHVU;
			}
			set
			{
				if ((this._MADICHVU != value))
				{
					this.OnMADICHVUChanging(value);
					this.SendPropertyChanging();
					this._MADICHVU = value;
					this.SendPropertyChanged("MADICHVU");
					this.OnMADICHVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDICHVU", DbType="NVarChar(MAX)")]
		public string TENDICHVU
		{
			get
			{
				return this._TENDICHVU;
			}
			set
			{
				if ((this._TENDICHVU != value))
				{
					this.OnTENDICHVUChanging(value);
					this.SendPropertyChanging();
					this._TENDICHVU = value;
					this.SendPropertyChanged("TENDICHVU");
					this.OnTENDICHVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA", DbType="NVarChar(50)")]
		public string GIA
		{
			get
			{
				return this._GIA;
			}
			set
			{
				if ((this._GIA != value))
				{
					this.OnGIAChanging(value);
					this.SendPropertyChanging();
					this._GIA = value;
					this.SendPropertyChanged("GIA");
					this.OnGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DICHVU_DANHSACHDV", Storage="_DANHSACHDVs", ThisKey="MADICHVU", OtherKey="MADICHVU")]
		public EntitySet<DANHSACHDV> DANHSACHDVs
		{
			get
			{
				return this._DANHSACHDVs;
			}
			set
			{
				this._DANHSACHDVs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANHSACHDVs(DANHSACHDV entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU = this;
		}
		
		private void detach_DANHSACHDVs(DANHSACHDV entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SOHD;
		
		private string _MATIECCUOI;
		
		private string _NGAYTHANHTOAN;
		
		private string _TONGTIENBAN;
		
		private string _TONGTIENDICHVU;
		
		private string _TONGTIENHOADON;
		
		private string _TIENCOC;
		
		private EntityRef<TIECCUOI> _TIECCUOI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSOHDChanging(string value);
    partial void OnSOHDChanged();
    partial void OnMATIECCUOIChanging(string value);
    partial void OnMATIECCUOIChanged();
    partial void OnNGAYTHANHTOANChanging(string value);
    partial void OnNGAYTHANHTOANChanged();
    partial void OnTONGTIENBANChanging(string value);
    partial void OnTONGTIENBANChanged();
    partial void OnTONGTIENDICHVUChanging(string value);
    partial void OnTONGTIENDICHVUChanged();
    partial void OnTONGTIENHOADONChanging(string value);
    partial void OnTONGTIENHOADONChanged();
    partial void OnTIENCOCChanging(string value);
    partial void OnTIENCOCChanged();
    #endregion
		
		public HOADON()
		{
			this._TIECCUOI = default(EntityRef<TIECCUOI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOHD", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SOHD
		{
			get
			{
				return this._SOHD;
			}
			set
			{
				if ((this._SOHD != value))
				{
					this.OnSOHDChanging(value);
					this.SendPropertyChanging();
					this._SOHD = value;
					this.SendPropertyChanged("SOHD");
					this.OnSOHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATIECCUOI", DbType="Char(20)")]
		public string MATIECCUOI
		{
			get
			{
				return this._MATIECCUOI;
			}
			set
			{
				if ((this._MATIECCUOI != value))
				{
					if (this._TIECCUOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATIECCUOIChanging(value);
					this.SendPropertyChanging();
					this._MATIECCUOI = value;
					this.SendPropertyChanged("MATIECCUOI");
					this.OnMATIECCUOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHANHTOAN", DbType="VarChar(50)")]
		public string NGAYTHANHTOAN
		{
			get
			{
				return this._NGAYTHANHTOAN;
			}
			set
			{
				if ((this._NGAYTHANHTOAN != value))
				{
					this.OnNGAYTHANHTOANChanging(value);
					this.SendPropertyChanging();
					this._NGAYTHANHTOAN = value;
					this.SendPropertyChanged("NGAYTHANHTOAN");
					this.OnNGAYTHANHTOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIENBAN", DbType="NVarChar(50)")]
		public string TONGTIENBAN
		{
			get
			{
				return this._TONGTIENBAN;
			}
			set
			{
				if ((this._TONGTIENBAN != value))
				{
					this.OnTONGTIENBANChanging(value);
					this.SendPropertyChanging();
					this._TONGTIENBAN = value;
					this.SendPropertyChanged("TONGTIENBAN");
					this.OnTONGTIENBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIENDICHVU", DbType="NVarChar(50)")]
		public string TONGTIENDICHVU
		{
			get
			{
				return this._TONGTIENDICHVU;
			}
			set
			{
				if ((this._TONGTIENDICHVU != value))
				{
					this.OnTONGTIENDICHVUChanging(value);
					this.SendPropertyChanging();
					this._TONGTIENDICHVU = value;
					this.SendPropertyChanged("TONGTIENDICHVU");
					this.OnTONGTIENDICHVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIENHOADON", DbType="NVarChar(50)")]
		public string TONGTIENHOADON
		{
			get
			{
				return this._TONGTIENHOADON;
			}
			set
			{
				if ((this._TONGTIENHOADON != value))
				{
					this.OnTONGTIENHOADONChanging(value);
					this.SendPropertyChanging();
					this._TONGTIENHOADON = value;
					this.SendPropertyChanged("TONGTIENHOADON");
					this.OnTONGTIENHOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIENCOC", DbType="NVarChar(50)")]
		public string TIENCOC
		{
			get
			{
				return this._TIENCOC;
			}
			set
			{
				if ((this._TIENCOC != value))
				{
					this.OnTIENCOCChanging(value);
					this.SendPropertyChanging();
					this._TIENCOC = value;
					this.SendPropertyChanged("TIENCOC");
					this.OnTIENCOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIECCUOI_HOADON", Storage="_TIECCUOI", ThisKey="MATIECCUOI", OtherKey="MATIECCUOI", IsForeignKey=true)]
		public TIECCUOI TIECCUOI
		{
			get
			{
				return this._TIECCUOI.Entity;
			}
			set
			{
				TIECCUOI previousValue = this._TIECCUOI.Entity;
				if (((previousValue != value) 
							|| (this._TIECCUOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TIECCUOI.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._TIECCUOI.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._MATIECCUOI = value.MATIECCUOI;
					}
					else
					{
						this._MATIECCUOI = default(string);
					}
					this.SendPropertyChanged("TIECCUOI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKHACHHANG;
		
		private string _TENCODAU;
		
		private string _TENCHURE;
		
		private string _SDT;
		
		private EntitySet<TIECCUOI> _TIECCUOIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHACHHANGChanging(string value);
    partial void OnMAKHACHHANGChanged();
    partial void OnTENCODAUChanging(string value);
    partial void OnTENCODAUChanged();
    partial void OnTENCHUREChanging(string value);
    partial void OnTENCHUREChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._TIECCUOIs = new EntitySet<TIECCUOI>(new Action<TIECCUOI>(this.attach_TIECCUOIs), new Action<TIECCUOI>(this.detach_TIECCUOIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHACHHANG", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKHACHHANG
		{
			get
			{
				return this._MAKHACHHANG;
			}
			set
			{
				if ((this._MAKHACHHANG != value))
				{
					this.OnMAKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._MAKHACHHANG = value;
					this.SendPropertyChanged("MAKHACHHANG");
					this.OnMAKHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCODAU", DbType="NVarChar(MAX)")]
		public string TENCODAU
		{
			get
			{
				return this._TENCODAU;
			}
			set
			{
				if ((this._TENCODAU != value))
				{
					this.OnTENCODAUChanging(value);
					this.SendPropertyChanging();
					this._TENCODAU = value;
					this.SendPropertyChanged("TENCODAU");
					this.OnTENCODAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCHURE", DbType="NVarChar(MAX)")]
		public string TENCHURE
		{
			get
			{
				return this._TENCHURE;
			}
			set
			{
				if ((this._TENCHURE != value))
				{
					this.OnTENCHUREChanging(value);
					this.SendPropertyChanging();
					this._TENCHURE = value;
					this.SendPropertyChanged("TENCHURE");
					this.OnTENCHUREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_TIECCUOI", Storage="_TIECCUOIs", ThisKey="MAKHACHHANG", OtherKey="MAKHACHHANG")]
		public EntitySet<TIECCUOI> TIECCUOIs
		{
			get
			{
				return this._TIECCUOIs;
			}
			set
			{
				this._TIECCUOIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TIECCUOIs(TIECCUOI entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_TIECCUOIs(TIECCUOI entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAISANH")]
	public partial class LOAISANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOAISANH;
		
		private string _TENLOAISANH;
		
		private string _DONGIABANTOITHIEU;
		
		private EntitySet<SANH> _SANHs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAISANHChanging(string value);
    partial void OnMALOAISANHChanged();
    partial void OnTENLOAISANHChanging(string value);
    partial void OnTENLOAISANHChanged();
    partial void OnDONGIABANTOITHIEUChanging(string value);
    partial void OnDONGIABANTOITHIEUChanged();
    #endregion
		
		public LOAISANH()
		{
			this._SANHs = new EntitySet<SANH>(new Action<SANH>(this.attach_SANHs), new Action<SANH>(this.detach_SANHs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAISANH", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAISANH
		{
			get
			{
				return this._MALOAISANH;
			}
			set
			{
				if ((this._MALOAISANH != value))
				{
					this.OnMALOAISANHChanging(value);
					this.SendPropertyChanging();
					this._MALOAISANH = value;
					this.SendPropertyChanged("MALOAISANH");
					this.OnMALOAISANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAISANH", DbType="NVarChar(MAX)")]
		public string TENLOAISANH
		{
			get
			{
				return this._TENLOAISANH;
			}
			set
			{
				if ((this._TENLOAISANH != value))
				{
					this.OnTENLOAISANHChanging(value);
					this.SendPropertyChanging();
					this._TENLOAISANH = value;
					this.SendPropertyChanged("TENLOAISANH");
					this.OnTENLOAISANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIABANTOITHIEU", DbType="NVarChar(50)")]
		public string DONGIABANTOITHIEU
		{
			get
			{
				return this._DONGIABANTOITHIEU;
			}
			set
			{
				if ((this._DONGIABANTOITHIEU != value))
				{
					this.OnDONGIABANTOITHIEUChanging(value);
					this.SendPropertyChanging();
					this._DONGIABANTOITHIEU = value;
					this.SendPropertyChanged("DONGIABANTOITHIEU");
					this.OnDONGIABANTOITHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAISANH_SANH", Storage="_SANHs", ThisKey="MALOAISANH", OtherKey="MALOAISANH")]
		public EntitySet<SANH> SANHs
		{
			get
			{
				return this._SANHs;
			}
			set
			{
				this._SANHs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SANHs(SANH entity)
		{
			this.SendPropertyChanging();
			entity.LOAISANH = this;
		}
		
		private void detach_SANHs(SANH entity)
		{
			this.SendPropertyChanging();
			entity.LOAISANH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MONAN")]
	public partial class MONAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAMONAN;
		
		private string _TENMONAN;
		
		private string _GIA;
		
		private EntitySet<THUCDON> _THUCDONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAMONANChanging(string value);
    partial void OnMAMONANChanged();
    partial void OnTENMONANChanging(string value);
    partial void OnTENMONANChanged();
    partial void OnGIAChanging(string value);
    partial void OnGIAChanged();
    #endregion
		
		public MONAN()
		{
			this._THUCDONs = new EntitySet<THUCDON>(new Action<THUCDON>(this.attach_THUCDONs), new Action<THUCDON>(this.detach_THUCDONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMONAN", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAMONAN
		{
			get
			{
				return this._MAMONAN;
			}
			set
			{
				if ((this._MAMONAN != value))
				{
					this.OnMAMONANChanging(value);
					this.SendPropertyChanging();
					this._MAMONAN = value;
					this.SendPropertyChanged("MAMONAN");
					this.OnMAMONANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENMONAN", DbType="NVarChar(MAX)")]
		public string TENMONAN
		{
			get
			{
				return this._TENMONAN;
			}
			set
			{
				if ((this._TENMONAN != value))
				{
					this.OnTENMONANChanging(value);
					this.SendPropertyChanging();
					this._TENMONAN = value;
					this.SendPropertyChanged("TENMONAN");
					this.OnTENMONANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA", DbType="NVarChar(50)")]
		public string GIA
		{
			get
			{
				return this._GIA;
			}
			set
			{
				if ((this._GIA != value))
				{
					this.OnGIAChanging(value);
					this.SendPropertyChanging();
					this._GIA = value;
					this.SendPropertyChanged("GIA");
					this.OnGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONAN_THUCDON", Storage="_THUCDONs", ThisKey="MAMONAN", OtherKey="MAMONAN")]
		public EntitySet<THUCDON> THUCDONs
		{
			get
			{
				return this._THUCDONs;
			}
			set
			{
				this._THUCDONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THUCDONs(THUCDON entity)
		{
			this.SendPropertyChanging();
			entity.MONAN = this;
		}
		
		private void detach_THUCDONs(THUCDON entity)
		{
			this.SendPropertyChanging();
			entity.MONAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SANH")]
	public partial class SANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MASANH;
		
		private string _MALOAISANH;
		
		private string _TENSANH;
		
		private System.Nullable<int> _SLBANTOIDA;
		
		private string _GHICHU;
		
		private EntitySet<TIECCUOI> _TIECCUOIs;
		
		private EntityRef<LOAISANH> _LOAISANH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASANHChanging(string value);
    partial void OnMASANHChanged();
    partial void OnMALOAISANHChanging(string value);
    partial void OnMALOAISANHChanged();
    partial void OnTENSANHChanging(string value);
    partial void OnTENSANHChanged();
    partial void OnSLBANTOIDAChanging(System.Nullable<int> value);
    partial void OnSLBANTOIDAChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    #endregion
		
		public SANH()
		{
			this._TIECCUOIs = new EntitySet<TIECCUOI>(new Action<TIECCUOI>(this.attach_TIECCUOIs), new Action<TIECCUOI>(this.detach_TIECCUOIs));
			this._LOAISANH = default(EntityRef<LOAISANH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASANH", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASANH
		{
			get
			{
				return this._MASANH;
			}
			set
			{
				if ((this._MASANH != value))
				{
					this.OnMASANHChanging(value);
					this.SendPropertyChanging();
					this._MASANH = value;
					this.SendPropertyChanged("MASANH");
					this.OnMASANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAISANH", DbType="Char(20)")]
		public string MALOAISANH
		{
			get
			{
				return this._MALOAISANH;
			}
			set
			{
				if ((this._MALOAISANH != value))
				{
					if (this._LOAISANH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAISANHChanging(value);
					this.SendPropertyChanging();
					this._MALOAISANH = value;
					this.SendPropertyChanged("MALOAISANH");
					this.OnMALOAISANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSANH", DbType="NVarChar(50)")]
		public string TENSANH
		{
			get
			{
				return this._TENSANH;
			}
			set
			{
				if ((this._TENSANH != value))
				{
					this.OnTENSANHChanging(value);
					this.SendPropertyChanging();
					this._TENSANH = value;
					this.SendPropertyChanged("TENSANH");
					this.OnTENSANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLBANTOIDA", DbType="Int")]
		public System.Nullable<int> SLBANTOIDA
		{
			get
			{
				return this._SLBANTOIDA;
			}
			set
			{
				if ((this._SLBANTOIDA != value))
				{
					this.OnSLBANTOIDAChanging(value);
					this.SendPropertyChanging();
					this._SLBANTOIDA = value;
					this.SendPropertyChanged("SLBANTOIDA");
					this.OnSLBANTOIDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(MAX)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANH_TIECCUOI", Storage="_TIECCUOIs", ThisKey="MASANH", OtherKey="MASANH")]
		public EntitySet<TIECCUOI> TIECCUOIs
		{
			get
			{
				return this._TIECCUOIs;
			}
			set
			{
				this._TIECCUOIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAISANH_SANH", Storage="_LOAISANH", ThisKey="MALOAISANH", OtherKey="MALOAISANH", IsForeignKey=true)]
		public LOAISANH LOAISANH
		{
			get
			{
				return this._LOAISANH.Entity;
			}
			set
			{
				LOAISANH previousValue = this._LOAISANH.Entity;
				if (((previousValue != value) 
							|| (this._LOAISANH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAISANH.Entity = null;
						previousValue.SANHs.Remove(this);
					}
					this._LOAISANH.Entity = value;
					if ((value != null))
					{
						value.SANHs.Add(this);
						this._MALOAISANH = value.MALOAISANH;
					}
					else
					{
						this._MALOAISANH = default(string);
					}
					this.SendPropertyChanged("LOAISANH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TIECCUOIs(TIECCUOI entity)
		{
			this.SendPropertyChanging();
			entity.SANH = this;
		}
		
		private void detach_TIECCUOIs(TIECCUOI entity)
		{
			this.SendPropertyChanging();
			entity.SANH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _TENTAIKHOAN;
		
		private string _MATKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnTENTAIKHOANChanging(string value);
    partial void OnTENTAIKHOANChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    #endregion
		
		public TAIKHOAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTAIKHOAN", DbType="VarChar(50)")]
		public string TENTAIKHOAN
		{
			get
			{
				return this._TENTAIKHOAN;
			}
			set
			{
				if ((this._TENTAIKHOAN != value))
				{
					this.OnTENTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._TENTAIKHOAN = value;
					this.SendPropertyChanged("TENTAIKHOAN");
					this.OnTENTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="VarChar(50)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUCDON")]
	public partial class THUCDON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATHUCDON;
		
		private string _MATIECCUOI;
		
		private string _MAMONAN;
		
		private string _GHICHU;
		
		private EntityRef<MONAN> _MONAN;
		
		private EntityRef<TIECCUOI> _TIECCUOI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHUCDONChanging(string value);
    partial void OnMATHUCDONChanged();
    partial void OnMATIECCUOIChanging(string value);
    partial void OnMATIECCUOIChanged();
    partial void OnMAMONANChanging(string value);
    partial void OnMAMONANChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    #endregion
		
		public THUCDON()
		{
			this._MONAN = default(EntityRef<MONAN>);
			this._TIECCUOI = default(EntityRef<TIECCUOI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUCDON", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHUCDON
		{
			get
			{
				return this._MATHUCDON;
			}
			set
			{
				if ((this._MATHUCDON != value))
				{
					this.OnMATHUCDONChanging(value);
					this.SendPropertyChanging();
					this._MATHUCDON = value;
					this.SendPropertyChanged("MATHUCDON");
					this.OnMATHUCDONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATIECCUOI", DbType="Char(20)")]
		public string MATIECCUOI
		{
			get
			{
				return this._MATIECCUOI;
			}
			set
			{
				if ((this._MATIECCUOI != value))
				{
					if (this._TIECCUOI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATIECCUOIChanging(value);
					this.SendPropertyChanging();
					this._MATIECCUOI = value;
					this.SendPropertyChanged("MATIECCUOI");
					this.OnMATIECCUOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMONAN", DbType="Char(20)")]
		public string MAMONAN
		{
			get
			{
				return this._MAMONAN;
			}
			set
			{
				if ((this._MAMONAN != value))
				{
					if (this._MONAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAMONANChanging(value);
					this.SendPropertyChanging();
					this._MAMONAN = value;
					this.SendPropertyChanged("MAMONAN");
					this.OnMAMONANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(MAX)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MONAN_THUCDON", Storage="_MONAN", ThisKey="MAMONAN", OtherKey="MAMONAN", IsForeignKey=true)]
		public MONAN MONAN
		{
			get
			{
				return this._MONAN.Entity;
			}
			set
			{
				MONAN previousValue = this._MONAN.Entity;
				if (((previousValue != value) 
							|| (this._MONAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MONAN.Entity = null;
						previousValue.THUCDONs.Remove(this);
					}
					this._MONAN.Entity = value;
					if ((value != null))
					{
						value.THUCDONs.Add(this);
						this._MAMONAN = value.MAMONAN;
					}
					else
					{
						this._MAMONAN = default(string);
					}
					this.SendPropertyChanged("MONAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIECCUOI_THUCDON", Storage="_TIECCUOI", ThisKey="MATIECCUOI", OtherKey="MATIECCUOI", IsForeignKey=true)]
		public TIECCUOI TIECCUOI
		{
			get
			{
				return this._TIECCUOI.Entity;
			}
			set
			{
				TIECCUOI previousValue = this._TIECCUOI.Entity;
				if (((previousValue != value) 
							|| (this._TIECCUOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TIECCUOI.Entity = null;
						previousValue.THUCDONs.Remove(this);
					}
					this._TIECCUOI.Entity = value;
					if ((value != null))
					{
						value.THUCDONs.Add(this);
						this._MATIECCUOI = value.MATIECCUOI;
					}
					else
					{
						this._MATIECCUOI = default(string);
					}
					this.SendPropertyChanged("TIECCUOI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
